# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0004_auto_20171011_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='menu',
        ),
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(blank=True, to='mycrm.Menu'),
        ),
    ]
