# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0005_auto_20171011_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='menu',
            new_name='menus',
        ),
    ]
